"use client";
import React, { useEffect, useMemo, useState, useSyncExternalStore } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { BarChart3, BookOpen, CalendarDays, CheckCircle2, ClipboardList, FileText, GraduationCap, LogOut, Menu, UploadCloud, X } from "lucide-react";
import { MOCK_ASSIGNMENTS, MOCK_COURSES } from "@/lib/mockData";
import { Assignment } from "@/lib/types";
import { DEFAULT_PORTAL_RECORDS, getPortalRecords, getStudentPortalRecords, subscribeToPortalRecords } from "@/lib/portalData";
import { StudentAccount } from "@/lib/types";
import { getStudentAssignments, saveStudentAssignments } from "@/lib/storage";

type Tab = "dashboard" | "results" | "timetable" | "courses" | "attendance" | "projects";
type Day = "Monday" | "Tuesday" | "Wednesday" | "Thursday" | "Friday";
const days: Day[] = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"];
const EMPTY_RECORDS = { results: [], attendance: [], schedule: [] };
function Heading({ title, description, icon: Icon }: { title: string; description: string; icon: typeof BookOpen }) { return <div className="mb-6"><h1 className="flex items-center gap-2 text-xl font-bold text-white"><Icon className="h-5 w-5 text-indigo-400" />{title}</h1><p className="mt-1 text-xs text-slate-400">{description}</p></div>; }
function getStudentSession(): StudentAccount | null { if (typeof window === "undefined") return null; try { return JSON.parse(window.sessionStorage.getItem("vva_student_account") || "null") as StudentAccount | null; } catch { return null; } }
const subscribeHydration = () => () => undefined;
const getHydratedSnapshot = () => true;

export default function StudentPortalPage() {
  const router = useRouter();
  const hydrated = useSyncExternalStore(subscribeHydration, getHydratedSnapshot, () => false);
  const studentAccount = useMemo(() => getStudentSession(), []);
  const studentName = studentAccount?.studentName || "Student";
  const studentId = studentAccount?.studentId || "Not assigned";
  const studentEmail = studentAccount?.studentEmail || "";
  const [tab, setTab] = useState<Tab>("dashboard"); const [day, setDay] = useState<Day>("Monday"); const [menu, setMenu] = useState(false); const [course, setCourse] = useState(MOCK_COURSES[0]); const [assignment, setAssignment] = useState<Assignment | null>(null); const [assignments, setAssignments] = useState<Assignment[]>([]); const [fileName, setFileName] = useState("");
  useEffect(() => { if (studentAccount) setAssignments(getStudentAssignments(studentId, [])); }, [studentAccount, studentId]);
  const getRecords = useMemo(() => studentAccount ? () => getStudentPortalRecords(studentId) : () => EMPTY_RECORDS, [studentAccount, studentId]);
  const records = useSyncExternalStore(subscribeToPortalRecords, getRecords, () => EMPTY_RECORDS);
  const numericScores = records.results.map((item) => Number.parseFloat(item.score)).filter((score) => Number.isFinite(score));
  const averageScore = numericScores.length ? numericScores.reduce((total, score) => total + score, 0) / numericScores.length : 0;
  const attendedSessions = records.attendance.filter((item) => item.status !== "Absent").length;
  const attendanceRate = records.attendance.length ? (attendedSessions / records.attendance.length) * 100 : 0;
  const formatPercent = (value: number) => `${value.toFixed(1).replace(/\.0$/, "")}%`;
  const nav = [{ key: "dashboard" as Tab, label: "Dashboard", icon: GraduationCap }, { key: "results" as Tab, label: "My Results", icon: BarChart3 }, { key: "timetable" as Tab, label: "My Timetable", icon: CalendarDays }, { key: "courses" as Tab, label: "Course Outline", icon: BookOpen }, { key: "attendance" as Tab, label: "Attendance", icon: CheckCircle2 }, { key: "projects" as Tab, label: "Project Instructions", icon: ClipboardList }];
  const openTab = (next: Tab) => { setTab(next); setMenu(false); };
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (!assignment || !fileName) return; const nextAssignments = assignments.map((item) => item.id === assignment.id ? { ...item, status: "submitted" as const } : item); setAssignments(nextAssignments); if (studentAccount) saveStudentAssignments(studentId, nextAssignments); setAssignment(null); setFileName(""); };
  const signOut = () => { window.sessionStorage.removeItem("vva_student_account"); router.replace("/login"); };
  if (!hydrated || !studentAccount) return <div className="flex min-h-screen items-center justify-center bg-slate-950 text-sm text-slate-400">Please sign in to access the student portal.</div>;
  return <div className="min-h-screen bg-slate-950 text-slate-100"><aside className={`fixed inset-y-0 left-0 z-40 w-64 border-r border-slate-800 bg-slate-900 transition-transform md:relative md:translate-x-0 ${menu ? "translate-x-0" : "-translate-x-full"}`}><div className="flex h-full flex-col"><div className="flex items-center justify-between border-b border-slate-800 p-5"><Link href="/" className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-indigo-600"><GraduationCap className="h-5 w-5" /></span><span><strong className="block text-sm text-white">Visioner Academy</strong><small className="text-[10px] uppercase text-indigo-400">Student Portal</small></span></Link><button onClick={() => setMenu(false)} aria-label="Close navigation" className="text-slate-400 md:hidden"><X className="h-5 w-5" /></button></div><div className="m-3 flex items-center gap-3 rounded-xl border border-slate-800 bg-slate-950 p-3"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-indigo-600 font-bold">AV</span><span><strong className="block text-xs text-white">{studentName}</strong><small className="text-[11px] text-slate-400">Year 12 • Cambridge AS</small></span></div><nav className="space-y-1 p-3">{nav.map(({ key, label, icon: Icon }) => <button key={key} onClick={() => openTab(key)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-xs font-semibold ${tab === key ? "bg-indigo-600 text-white" : "text-slate-400 hover:bg-slate-800 hover:text-white"}`}><Icon className="h-4 w-4" />{label}</button>)}</nav><div className="mt-auto space-y-2 border-t border-slate-800 p-4"><Link href="/owner" className="block px-3 py-2 text-xs text-indigo-300 hover:bg-slate-800">Owner dashboard</Link><button type="button" onClick={signOut} className="flex items-center gap-2 px-3 py-2 text-xs text-slate-400 hover:text-white"><LogOut className="h-4 w-4" />Sign out</button></div></div></aside><div className="flex min-h-screen flex-1 flex-col md:absolute md:left-64 md:right-0 md:top-0"><header className="sticky top-0 z-30 flex items-center justify-between border-b border-slate-800 bg-slate-900 px-4 py-4 sm:px-6"><button onClick={() => setMenu(true)} aria-label="Open navigation" className="rounded-lg bg-slate-800 p-2 md:hidden"><Menu className="h-5 w-5" /></button><span className="text-xs font-semibold text-slate-400">Academic Year 2026 / 2027</span><span className="text-xs text-slate-300">{studentEmail}</span></header><main className="mx-auto w-full max-w-6xl flex-1 p-4 sm:p-6 lg:p-8">
    {tab === "dashboard" && <><Heading title={`Welcome back, ${studentName}`} description={`Student ID: ${studentId} � Your academic workspace contains only the records and tasks you need.`} icon={GraduationCap} /><div className="grid gap-4 sm:grid-cols-3"><button onClick={() => openTab("results")} className="rounded-2xl border border-slate-800 bg-slate-900 p-5 text-left"><span className="text-xs text-slate-400">Term average</span><strong className="mt-2 block text-2xl text-emerald-400">{formatPercent(averageScore)}</strong><small className="text-xs text-slate-500">Calculated from {records.results.length} published results</small></button><button onClick={() => openTab("attendance")} className="rounded-2xl border border-slate-800 bg-slate-900 p-5 text-left"><span className="text-xs text-slate-400">Attendance</span><strong className="mt-2 block text-2xl text-indigo-300">{formatPercent(attendanceRate)}</strong><small className="text-xs text-slate-500">{attendedSessions} of {records.attendance.length} sessions attended</small></button><button onClick={() => openTab("projects")} className="rounded-2xl border border-slate-800 bg-slate-900 p-5 text-left"><span className="text-xs text-slate-400">Project tasks</span><strong className="mt-2 block text-2xl text-amber-400">{assignments.filter((item) => item.status === "pending").length}</strong><small className="text-xs text-slate-500">Awaiting your submission</small></button></div></>}
    {tab === "results" && <><Heading title="My Results" description="Current marks and teacher feedback." icon={BarChart3} /><div className="overflow-x-auto rounded-2xl border border-slate-800 bg-slate-900"><table className="w-full min-w-162.5 text-left text-xs"><thead className="bg-slate-950 text-[10px] uppercase text-slate-400"><tr><th className="p-4">Course</th><th className="p-4">Score</th><th className="p-4">Grade</th><th className="p-4">Feedback</th></tr></thead><tbody className="divide-y divide-slate-800">{records.results.map((item) => <tr key={item.id}><td className="p-4"><span className="font-mono text-indigo-400">{item.code}</span><strong className="mt-1 block text-white">{item.course}</strong></td><td className="p-4 font-bold text-emerald-400">{item.score}</td><td className="p-4 font-bold text-emerald-400">{item.grade}</td><td className="p-4 text-slate-400">{item.feedback}</td></tr>)}</tbody></table></div></>}
    {tab === "timetable" && <><Heading title="My Timetable" description="Your weekly class schedule in Gulf Standard Time." icon={CalendarDays} /><div className="mb-4 flex flex-wrap gap-2">{days.map((item) => <button key={item} onClick={() => setDay(item)} className={`rounded-lg px-4 py-2 text-xs font-semibold ${day === item ? "bg-indigo-600 text-white" : "border border-slate-800 bg-slate-900 text-slate-400"}`}>{item}</button>)}</div><div className="space-y-3">{records.schedule.filter((item) => item.day === day).map((item) => <div key={item.id} className="flex flex-col gap-2 rounded-2xl border border-slate-800 bg-slate-900 p-4 sm:flex-row sm:items-center"><span className="w-36 text-xs font-bold text-indigo-300">{item.time}</span><div><h2 className="text-sm font-bold text-white">{item.course}</h2><p className="text-xs text-slate-400">{item.topic} • {item.teacher}</p></div></div>)}</div></>}
    {tab === "courses" && <><Heading title="Course Outline" description="Review the syllabus for each enrolled course." icon={BookOpen} /><div className="grid gap-4 md:grid-cols-2">{MOCK_COURSES.slice(0, 4).map((item) => <button key={item.id} onClick={() => setCourse(item)} className={`rounded-2xl border p-5 text-left ${course.id === item.id ? "border-indigo-500 bg-indigo-950/30" : "border-slate-800 bg-slate-900"}`}><span className="font-mono text-xs text-indigo-400">{item.code}</span><h2 className="mt-2 text-sm font-bold text-white">{item.title}</h2><p className="mt-2 text-xs text-slate-400">{item.instructor}</p></button>)}</div><div className="mt-4 rounded-2xl border border-slate-800 bg-slate-900 p-5"><h2 className="text-base font-bold text-white">{course.title}</h2><p className="mt-2 text-xs text-slate-400">{course.description}</p><ul className="mt-5 grid gap-2 text-xs text-slate-300 sm:grid-cols-2">{course.syllabus.map((item) => <li key={item} className="flex gap-2"><CheckCircle2 className="h-4 w-4 shrink-0 text-emerald-400" />{item}</li>)}</ul></div></>}
    {tab === "attendance" && <><Heading title="Attendance" description="A record of your recent class attendance." icon={CheckCircle2} /><div className="mb-5 rounded-2xl border border-emerald-500/30 bg-emerald-950/20 p-5"><span className="text-xs text-slate-400">Overall attendance</span><strong className="mt-1 block text-3xl text-emerald-400">{formatPercent(attendanceRate)}</strong><span className="mt-1 block text-xs text-slate-400">{attendedSessions} of {records.attendance.length} sessions attended</span></div><div className="space-y-3">{records.attendance.map((item) => <div key={item.id} className="flex items-center justify-between rounded-2xl border border-slate-800 bg-slate-900 p-4"><div><h2 className="text-sm font-bold text-white">{item.course}</h2><p className="text-xs text-slate-400">{item.date}</p></div><span className={`text-xs font-bold ${item.status === "Present" ? "text-emerald-400" : item.status === "Late" ? "text-amber-400" : "text-rose-400"}`}>{item.status}</span></div>)}</div></>}
    {tab === "projects" && <><Heading title="Project Instructions" description="Read each brief, then upload your completed work for review." icon={ClipboardList} /><div className="space-y-4">{assignments.map((item) => <div key={item.id} className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><span className="font-mono text-xs text-indigo-400">{item.courseCode}</span><h2 className="mt-2 text-base font-bold text-white">{item.title}</h2><p className="mt-2 max-w-2xl text-xs leading-relaxed text-slate-400">{item.instructions}</p><p className="mt-3 text-xs text-slate-300">Due: <strong>{item.dueDate}</strong></p></div>{item.status === "submitted" ? <span className="flex items-center gap-1 text-xs font-bold text-emerald-400"><CheckCircle2 className="h-4 w-4" />Submitted</span> : <button onClick={() => setAssignment(item)} className="flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 text-xs font-bold text-white"><UploadCloud className="h-4 w-4" />Submit project</button>}</div></div>)}</div></>}
  </main></div>{assignment && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/80 p-4"><form onSubmit={submit} className="w-full max-w-md space-y-5 rounded-2xl border border-slate-800 bg-slate-900 p-6"><div className="flex items-center justify-between"><h2 className="text-sm font-bold text-white">Submit project</h2><button type="button" onClick={() => setAssignment(null)} aria-label="Close submission dialog"><X className="h-5 w-5 text-slate-400" /></button></div><p className="text-xs text-slate-400">{assignment.title}</p><label className="flex cursor-pointer flex-col items-center gap-2 rounded-xl border-2 border-dashed border-slate-700 bg-slate-950 p-6 text-center"><FileText className="h-7 w-7 text-indigo-400" /><span className="text-xs text-white">{fileName || "Choose your completed project"}</span><input required type="file" onChange={(event) => setFileName(event.target.files?.[0]?.name || "")} className="sr-only" accept=".pdf,.doc,.docx,.zip,.py,.png,.jpg" /></label><button type="submit" className="w-full rounded-xl bg-indigo-600 py-3 text-xs font-bold text-white">Confirm submission</button></form></div>}</div>;
}







