"use client";

import React, { FormEvent, useEffect, useSyncExternalStore, useState } from "react";
import { Award, BookOpen, CalendarDays, CheckCircle2, ClipboardList, GraduationCap, LogOut, Plus, Save, Trash2, Users } from "lucide-react";
import { loginOwner, clearPortalSession, getPortalSession, savePortalSession } from "@/lib/auth";
import { getSavedApplications, getStudentAccounts, saveStudentAccount, getStudentAssignments, saveStudentAssignments } from "@/lib/storage";
import { AdmissionsApplication, StudentAccount, Assignment } from "@/lib/types";
import { AcademicResult, AttendanceRecord, PortalRecords, ScheduleRecord, getStudentPortalRecords, saveStudentPortalRecords } from "@/lib/portalData";

type Tab = "overview" | "students" | "assignments" | "academic" | "timetable" | "attendance";
const ownerSnapshot = () => typeof window !== "undefined" && getPortalSession()?.role === "owner";
const ownerSubscribe = (fn: () => void) => { const h = () => fn(); window.addEventListener("storage", h); window.addEventListener("vva_auth_changed", h); return () => { window.removeEventListener("storage", h); window.removeEventListener("vva_auth_changed", h); }; };
const input = "w-full rounded-xl border border-slate-800 bg-slate-950 px-3 py-2.5 text-sm outline-none focus:border-indigo-500";
const emptyResult: AcademicResult = { id: "", course: "", code: "", score: "", grade: "", feedback: "" };
const emptyAttendance: AttendanceRecord = { id: "", date: "", course: "", status: "Present", totalClasses: 1, attended: 1 };
const emptySchedule: ScheduleRecord = { id: "", day: "Monday", time: "", subject: "", course: "", teacher: "", room: "" };

export default function OwnerPage() {
  const authenticated = useSyncExternalStore(ownerSubscribe, ownerSnapshot, () => false);
  const [ownerId, setOwnerId] = useState(""); const [ownerPassword, setOwnerPassword] = useState(""); const [loginError, setLoginError] = useState("");
  const [tab, setTab] = useState<Tab>("overview"); const [message, setMessage] = useState("");
  const [applications, setApplications] = useState<AdmissionsApplication[]>([]); const [accounts, setAccounts] = useState<StudentAccount[]>([]);
  const [selectedId, setSelectedId] = useState(""); const [records, setRecords] = useState<PortalRecords | null>(null); const [assignments, setAssignments] = useState<Assignment[]>([]);
  const [assignment, setAssignment] = useState<Assignment>({ id: "", title: "", course: "", courseCode: "", dueDate: "", status: "pending", instructions: "", score: "100 pts", urgency: "normal" });
  const [result, setResult] = useState<AcademicResult>(emptyResult); const [editingResult, setEditingResult] = useState<string | null>(null);
  const [attendance, setAttendance] = useState<AttendanceRecord>(emptyAttendance); const [editingAttendance, setEditingAttendance] = useState<string | null>(null);
  const [schedule, setSchedule] = useState<ScheduleRecord>(emptySchedule); const [editingSchedule, setEditingSchedule] = useState<string | null>(null);
  const [subjectName, setSubjectName] = useState(""); const [subjectCode, setSubjectCode] = useState("");

  const notify = (text: string) => { setMessage(text); window.setTimeout(() => setMessage(""), 3000); };
  const loadStudent = async (id: string) => { if (!id) return; setSelectedId(id); const [r, a] = await Promise.all([getStudentPortalRecords(id), getStudentAssignments(id, [])]); setRecords(r); setAssignments(a); };
  const load = async () => { const [apps, accts] = await Promise.all([getSavedApplications(), getStudentAccounts()]); setApplications(apps); setAccounts(accts); const first = accts[0]?.studentId || apps[0]?.id || ""; if (first) await loadStudent(first); };
  useEffect(() => { if (authenticated) load(); }, [authenticated]);
  useEffect(() => { if (!authenticated || !selectedId) return; const timer = window.setInterval(() => loadStudent(selectedId), 5000); return () => window.clearInterval(timer); }, [authenticated, selectedId]);

  const selectedAccount = accounts.find(a => a.studentId === selectedId); const selectedApp = applications.find(a => a.id === selectedId || a.id === selectedAccount?.applicationId);
  const subjects = records?.subjects || [];
  const avg = records?.results?.length ? Math.round(records.results.reduce((s, r) => s + (Number.parseFloat(String(r.score || "").replace(/[^0-9.]/g, "")) || 0), 0) / records.results.length) : 0;
  const attPct = records?.attendance?.length ? Math.round(records.attendance.filter(a => String(a.status).toLowerCase() === "present").length / records.attendance.length * 100) : 0;

  async function ownerLogin(e: FormEvent) { e.preventDefault(); setLoginError(""); const user = await loginOwner(ownerId, ownerPassword); if (!user) { setLoginError("Invalid owner username/email or password."); return; } savePortalSession(user); window.dispatchEvent(new Event("vva_auth_changed")); }
  function signOut() { clearPortalSession(); window.dispatchEvent(new Event("vva_auth_changed")); }
  async function ensureAccount(app: AdmissionsApplication) { const old = accounts.find(a => a.applicationId === app.id || a.studentId === app.id); const account = old || { applicationId: app.id, studentId: app.id, password: `VVA${Math.floor(100000 + Math.random()*900000)}`, studentName: app.studentName, studentEmail: app.studentEmail, createdAt: new Date().toISOString() }; await saveStudentAccount(account); setAccounts(await getStudentAccounts()); await loadStudent(account.studentId); notify(`Student account ready: ${account.studentId}`); }
  async function saveRecords(next: PortalRecords) { if (!selectedId) return; const clean = { ...next, stats: { ...next.stats, averagePerformance: `${avg}%`, classAttendance: `${attPct}%`, pendingHomework: assignments.filter(a => a.status === "pending").length, activeSubjectsCount: (next.subjects || []).length } }; setRecords(clean); await saveStudentPortalRecords(selectedId, clean); notify("Saved to Supabase. Student portal updated globally."); }

  async function createAssignment(e: FormEvent) { e.preventDefault(); if (!assignment.title || !assignment.course) return; const item = { ...assignment, id: assignment.id || `asg-${Date.now()}`, status: assignment.status || "pending" }; const next = assignment.id ? assignments.map(a => a.id === assignment.id ? item : a) : [item, ...assignments]; setAssignments(next); await saveStudentAssignments(selectedId, next); setAssignment({ id:"", title:"", course:"", courseCode:"", dueDate:"", status:"pending", instructions:"", score:"100 pts", urgency:"normal" }); notify("Assignment published globally."); }
  async function deleteAssignment(id: string) { const next = assignments.filter(a => a.id !== id); setAssignments(next); await saveStudentAssignments(selectedId, next); notify("Assignment removed globally."); }
  async function gradeAssignment(a: Assignment) { const score = window.prompt("Enter score", a.score || ""); if (score === null) return; const feedback = window.prompt("Feedback", a.feedback || "") ?? ""; const next = assignments.map(x => x.id === a.id ? { ...x, score, feedback, status: "graded" } : x); setAssignments(next); await saveStudentAssignments(selectedId, next); notify("Assignment grade published globally."); }

  async function saveResult(e: FormEvent) { e.preventDefault(); if (!result.course || !result.score || !records) return; const item = { ...result, id: editingResult || `result-${Date.now()}` }; const next = editingResult ? records.results.map(r => r.id === editingResult ? item : r) : [...records.results, item]; await saveRecords({ ...records, results: next, recentResults: next.slice(-5).reverse() }); setResult(emptyResult); setEditingResult(null); }
  async function deleteResult(id: string) { if (records) await saveRecords({ ...records, results: records.results.filter(r => r.id !== id) }); }
  async function saveAttendance(e: FormEvent) { e.preventDefault(); if (!attendance.course || !attendance.date || !records) return; const total = Number(attendance.totalClasses || 1); const attended = Number(attendance.attended ?? (attendance.status === "Present" ? total : 0)); const item = { ...attendance, id: editingAttendance || `att-${Date.now()}`, totalClasses: total, attended, percentage: total ? `${Math.round(attended/total*100)}%` : "0%" }; const next = editingAttendance ? records.attendance.map(a => a.id === editingAttendance ? item : a) : [...records.attendance, item]; await saveRecords({ ...records, attendance: next }); setAttendance(emptyAttendance); setEditingAttendance(null); }
  async function deleteAttendance(id: string) { if (records) await saveRecords({ ...records, attendance: records.attendance.filter(a => a.id !== id) }); }
  async function saveSchedule(e: FormEvent) { e.preventDefault(); if (!schedule.subject || !schedule.time || !records) return; const item = { ...schedule, id: editingSchedule || `schedule-${Date.now()}`, course: schedule.course || schedule.subject }; const next = editingSchedule ? records.schedule.map(s => s.id === editingSchedule ? item : s) : [...records.schedule, item]; await saveRecords({ ...records, schedule: next, timetable: next }); setSchedule(emptySchedule); setEditingSchedule(null); }
  async function deleteSchedule(id: string) { if (!records) return; const next = records.schedule.filter(s => s.id !== id); await saveRecords({ ...records, schedule: next, timetable: next }); }
  async function addSubject() { const name = subjectName.trim(); if (!name || !records) return; const value = subjectCode.trim() ? `${name} (${subjectCode.trim()})` : name; if (subjects.includes(value)) return; await saveRecords({ ...records, subjects: [...subjects, value] }); setSubjectName(""); setSubjectCode(""); }
  async function removeSubject(value: string) { if (records) await saveRecords({ ...records, subjects: subjects.filter(s => s !== value) }); }

  if (!authenticated) return <main className="min-h-screen bg-slate-950 text-white grid place-items-center p-4"><form onSubmit={ownerLogin} className="w-full max-w-md rounded-3xl border border-slate-800 bg-slate-900 p-8"><div className="text-center mb-7"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-indigo-600"><GraduationCap/></div><h1 className="mt-4 text-2xl font-black">Visioner Owner Portal</h1><p className="mt-1 text-xs text-slate-400">Manage every student record globally</p></div>{loginError && <div className="mb-4 rounded-xl bg-rose-500/10 p-3 text-xs text-rose-300">{loginError}</div>}<input className={input+" mb-3"} value={ownerId} onChange={e=>setOwnerId(e.target.value)} placeholder="Owner username or email" required/><input className={input+" mb-4"} type="password" value={ownerPassword} onChange={e=>setOwnerPassword(e.target.value)} placeholder="Password" required/><button className="w-full rounded-xl bg-indigo-600 py-3 text-sm font-bold">Sign In</button><p className="mt-4 text-center text-[11px] text-slate-500">Demo owner: owner / admin123</p></form></main>;

  const tabs: [Tab,string,any][] = [["overview","Overview",Award],["students","Students",Users],["assignments","Assignments",ClipboardList],["academic","Subjects & Results",BookOpen],["timetable","Timetable",CalendarDays],["attendance","Attendance",CheckCircle2]];
  return <main className="min-h-screen bg-slate-950 text-slate-100"><header className="sticky top-0 z-20 border-b border-slate-800 bg-slate-950/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between p-4"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-indigo-600"><GraduationCap size={20}/></div><div><b className="block text-sm">Visioner Virtual Academy</b><span className="text-[10px] text-indigo-400">OWNER PORTAL • GLOBAL DATA</span></div></div><button onClick={signOut} className="flex items-center gap-2 rounded-xl bg-slate-800 px-3 py-2 text-xs font-bold"><LogOut size={14}/> Sign Out</button></div></header>
  <div className="mx-auto max-w-7xl p-4 sm:p-7"><div className="mb-5 flex flex-col gap-3 rounded-2xl border border-slate-800 bg-slate-900 p-4 md:flex-row md:items-center md:justify-between"><div><p className="text-[11px] text-slate-500">ACTIVE STUDENT</p><b>{selectedAccount?.studentName || selectedApp?.studentName || "No student selected"}</b><p className="text-xs text-slate-500">{selectedId || "Select a student from Students"}</p></div><select value={selectedId} onChange={e=>loadStudent(e.target.value)} className="rounded-xl border border-slate-800 bg-slate-950 px-3 py-2 text-sm md:w-80"><option value="">Select student</option>{accounts.map(a=><option key={a.studentId} value={a.studentId}>{a.studentName} • {a.studentId}</option>)}{applications.filter(a=>!accounts.some(x=>x.studentId===a.id)).map(a=><option key={a.id} value={a.id}>{a.studentName} • no account</option>)}</select></div>
  <nav className="mb-6 flex gap-2 overflow-x-auto">{tabs.map(([k,label,Icon])=><button key={k} onClick={()=>setTab(k)} className={`flex shrink-0 items-center gap-2 rounded-xl px-4 py-2.5 text-xs font-bold ${tab===k?"bg-indigo-600 text-white":"border border-slate-800 bg-slate-900 text-slate-400"}`}><Icon size={15}/>{label}</button>)}</nav>
  {!selectedId ? <div className="rounded-2xl border border-slate-800 bg-slate-900 p-10 text-center text-sm text-slate-400">Create/generate a student account or select an existing student.</div> : !records ? <div className="rounded-2xl border border-slate-800 bg-slate-900 p-10 text-center text-sm text-slate-400">Loading student data...</div> : <>
  {tab==="overview" && <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Average Result",`${avg}%`,Award],["Pending Assignments",assignments.filter(a=>a.status==="pending").length,ClipboardList],["Attendance",`${attPct}%`,CheckCircle2],["Active Subjects",subjects.length,BookOpen]].map(([l,v,I]:any)=><div key={l} className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><I size={18} className="text-indigo-400"/><p className="mt-4 text-xs text-slate-500">{l}</p><b className="mt-1 block text-2xl">{v}</b></div>)}</div>}
  {tab==="students" && <div className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><h2 className="font-bold">Student accounts</h2><div className="mt-4 grid gap-3">{applications.map(a=>{const ac=accounts.find(x=>x.applicationId===a.id||x.studentId===a.id);return <div key={a.id} className="flex flex-col gap-3 rounded-xl border border-slate-800 bg-slate-950 p-4 md:flex-row md:items-center md:justify-between"><div><b>{a.studentName}</b><p className="text-xs text-slate-500">{a.studentEmail} • {a.id}</p></div>{ac?<button onClick={()=>loadStudent(ac.studentId)} className="rounded-lg bg-indigo-600 px-3 py-2 text-xs font-bold">Open Portal Data</button>:<button onClick={()=>ensureAccount(a)} className="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold">Generate Account</button>}</div>})}</div></div>}
  {tab==="assignments" && <div className="grid gap-5 lg:grid-cols-[380px,1fr]"><form onSubmit={createAssignment} className="rounded-2xl border border-slate-800 bg-slate-900 p-5 space-y-3"><h2 className="font-bold">{assignment.id?"Edit":"Create"} assignment</h2><input className={input} value={assignment.title} onChange={e=>setAssignment({...assignment,title:e.target.value})} placeholder="Assignment title" required/><input className={input} value={assignment.course} onChange={e=>setAssignment({...assignment,course:e.target.value})} placeholder="Subject / course" required/><input className={input} value={assignment.courseCode} onChange={e=>setAssignment({...assignment,courseCode:e.target.value})} placeholder="Subject code"/><input className={input} type="date" value={assignment.dueDate} onChange={e=>setAssignment({...assignment,dueDate:e.target.value})}/><input className={input} value={assignment.score} onChange={e=>setAssignment({...assignment,score:e.target.value})} placeholder="Marks e.g. 100 pts"/><select className={input} value={assignment.urgency} onChange={e=>setAssignment({...assignment,urgency:e.target.value})}><option value="normal">Normal</option><option value="high">High priority</option></select><textarea className={input+" min-h-28"} value={assignment.instructions} onChange={e=>setAssignment({...assignment,instructions:e.target.value})} placeholder="Instructions"/><button className="w-full rounded-xl bg-indigo-600 py-3 text-xs font-bold"><Save size={14} className="inline mr-1"/>{assignment.id?"Update":"Publish"}</button></form><div className="space-y-3">{assignments.map(a=><div key={a.id} className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="flex justify-between gap-3"><div><b>{a.title}</b><p className="mt-1 text-xs text-slate-500">{a.course} • Due {a.dueDate || "—"}</p></div><span className="text-[10px] uppercase text-indigo-300">{a.status}</span></div><p className="mt-3 text-xs text-slate-400">{a.instructions}</p>{a.score&&<p className="mt-2 text-xs text-emerald-300">Score: {a.score}{a.feedback?` • ${a.feedback}`:""}</p>}<div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>setAssignment(a)} className="rounded-lg bg-slate-800 px-3 py-2 text-xs">Edit</button><button onClick={()=>gradeAssignment(a)} className="rounded-lg bg-indigo-600 px-3 py-2 text-xs">Grade</button><button onClick={()=>deleteAssignment(a.id)} className="rounded-lg bg-rose-600/80 px-3 py-2 text-xs">Delete</button></div></div>)}</div></div>}
  {tab==="academic" && <div className="space-y-5"><div className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><h2 className="font-bold">Subjects</h2><div className="mt-3 flex flex-col gap-2 md:flex-row"><input className={input} value={subjectName} onChange={e=>setSubjectName(e.target.value)} placeholder="Subject name"/><input className={input} value={subjectCode} onChange={e=>setSubjectCode(e.target.value)} placeholder="Code"/><button onClick={addSubject} className="rounded-xl bg-indigo-600 px-5 py-2 text-xs font-bold"><Plus size={14} className="inline"/> Add</button></div><div className="mt-4 flex flex-wrap gap-2">{subjects.map(s=><span key={s} className="flex items-center gap-2 rounded-full bg-slate-950 px-3 py-2 text-xs">{s}<button onClick={()=>removeSubject(s)}><Trash2 size={12}/></button></span>)}</div></div><div className="grid gap-5 lg:grid-cols-[380px,1fr]"><form onSubmit={saveResult} className="rounded-2xl border border-slate-800 bg-slate-900 p-5 space-y-3"><h2 className="font-bold">{editingResult?"Edit":"Add"} result</h2><input className={input} value={result.course||result.subject||""} onChange={e=>setResult({...result,course:e.target.value,subject:e.target.value})} placeholder="Subject" required/><input className={input} value={result.code||""} onChange={e=>setResult({...result,code:e.target.value})} placeholder="Subject code"/><input className={input} value={result.score||""} onChange={e=>setResult({...result,score:e.target.value})} placeholder="Score e.g. 94 / 100" required/><input className={input} value={result.grade||""} onChange={e=>setResult({...result,grade:e.target.value})} placeholder="Grade e.g. A"/><textarea className={input} value={result.feedback||""} onChange={e=>setResult({...result,feedback:e.target.value})} placeholder="Feedback"/><button className="w-full rounded-xl bg-indigo-600 py-3 text-xs font-bold"><Save size={14} className="inline mr-1"/>{editingResult?"Update result":"Publish result"}</button></form><div className="space-y-3">{records.results.map(r=><div key={r.id} className="flex items-center justify-between gap-3 rounded-xl border border-slate-800 bg-slate-900 p-4"><div><b>{r.course||r.subject}</b><p className="text-xs text-slate-500">{r.code} • {r.feedback||""}</p></div><div className="flex items-center gap-2"><strong className="text-indigo-300">{r.score||r.grade}</strong><button onClick={()=>{setResult(r);setEditingResult(r.id)}} className="rounded-lg bg-slate-800 p-2"><Save size={13}/></button><button onClick={()=>deleteResult(r.id)} className="rounded-lg bg-rose-600/80 p-2"><Trash2 size={13}/></button></div></div>)}</div></div></div>}
  {tab==="timetable" && <div className="grid gap-5 lg:grid-cols-[380px,1fr]"><form onSubmit={saveSchedule} className="rounded-2xl border border-slate-800 bg-slate-900 p-5 space-y-3"><h2 className="font-bold">{editingSchedule?"Edit":"Add"} timetable class</h2><select className={input} value={schedule.day} onChange={e=>setSchedule({...schedule,day:e.target.value})}>{["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"].map(d=><option key={d}>{d}</option>)}</select><input className={input} value={schedule.time||""} onChange={e=>setSchedule({...schedule,time:e.target.value})} placeholder="09:00 AM - 10:30 AM" required/><input className={input} value={schedule.subject||""} onChange={e=>setSchedule({...schedule,subject:e.target.value})} placeholder="Subject" required/><input className={input} value={schedule.teacher||""} onChange={e=>setSchedule({...schedule,teacher:e.target.value})} placeholder="Teacher"/><input className={input} value={schedule.room||""} onChange={e=>setSchedule({...schedule,room:e.target.value})} placeholder="Room / online link"/><button className="w-full rounded-xl bg-indigo-600 py-3 text-xs font-bold"><Save size={14} className="inline mr-1"/>{editingSchedule?"Update":"Publish"}</button></form><div className="space-y-3">{records.schedule.map(s=><div key={s.id} className="flex items-center justify-between gap-3 rounded-xl border border-slate-800 bg-slate-900 p-4"><div><b>{s.day} • {s.time}</b><p className="mt-1 text-xs text-indigo-300">{s.subject||s.course}</p><p className="text-xs text-slate-500">{s.teacher||"Faculty"}{s.room?` • ${s.room}`:""}</p></div><div className="flex gap-2"><button onClick={()=>{setSchedule(s);setEditingSchedule(String(s.id))}} className="rounded-lg bg-slate-800 px-3 py-2 text-xs">Edit</button><button onClick={()=>deleteSchedule(String(s.id))} className="rounded-lg bg-rose-600/80 px-3 py-2 text-xs">Delete</button></div></div>)}</div></div>}
  {tab==="attendance" && <div className="grid gap-5 lg:grid-cols-[380px,1fr]"><form onSubmit={saveAttendance} className="rounded-2xl border border-slate-800 bg-slate-900 p-5 space-y-3"><h2 className="font-bold">{editingAttendance?"Edit":"Add"} attendance</h2><input className={input} type="date" value={attendance.date||""} onChange={e=>setAttendance({...attendance,date:e.target.value})} required/><input className={input} value={attendance.course||""} onChange={e=>setAttendance({...attendance,course:e.target.value,subject:e.target.value})} placeholder="Subject" required/><select className={input} value={attendance.status||"Present"} onChange={e=>setAttendance({...attendance,status:e.target.value})}><option>Present</option><option>Absent</option><option>Late</option><option>Leave</option></select><div className="grid grid-cols-2 gap-2"><input className={input} type="number" min="1" value={attendance.totalClasses??1} onChange={e=>setAttendance({...attendance,totalClasses:Number(e.target.value)})} placeholder="Total classes"/><input className={input} type="number" min="0" value={attendance.attended??0} onChange={e=>setAttendance({...attendance,attended:Number(e.target.value)})} placeholder="Attended"/></div><button className="w-full rounded-xl bg-indigo-600 py-3 text-xs font-bold"><Save size={14} className="inline mr-1"/>{editingAttendance?"Update":"Save"}</button></form><div className="space-y-3">{records.attendance.map(a=><div key={a.id} className="flex items-center justify-between gap-3 rounded-xl border border-slate-800 bg-slate-900 p-4"><div><b>{a.course||a.subject}</b><p className="text-xs text-slate-500">{a.date} • {a.percentage || `${a.attended||0}/${a.totalClasses||0}`}</p></div><div className="flex items-center gap-2"><span className="text-xs text-emerald-300">{a.status}</span><button onClick={()=>{setAttendance(a);setEditingAttendance(a.id)}} className="rounded-lg bg-slate-800 p-2"><Save size={13}/></button><button onClick={()=>deleteAttendance(a.id)} className="rounded-lg bg-rose-600/80 p-2"><Trash2 size={13}/></button></div></div>)}</div></div>}
  </>}</div>{message&&<div className="fixed bottom-5 right-5 rounded-xl border border-emerald-500/30 bg-emerald-950 px-4 py-3 text-xs text-emerald-300 shadow-xl">{message}</div>}</div></main>;
}
