import { Course, FacultyMember, Assignment, TimetableEntry } from "./types";

export const MOCK_COURSES: Course[] = [
  {
    id: "CRS-4109",
    code: "VVA-EX792-CHM",
    title: "CHEMISTRY",
    track: "cambridge-a-levels",
    trackLabel: "Ziauddin",
    department: "Sciences",
    gradeLevel: "Grade 9 - 10",
    weeklyHours: 5,
    instructor: "Wara Batool",
    instructorTitle: "M.Phill. in Chemistry / Physical Sciences",
    description:
      "Our Chemistry teachings is designed to make challenging topics simple, understandable, and engaging. Students receive personalised guidance from experienced tutors with a focus on conceptual understanding and exam preparation.",
    syllabus: [
      "Chemical Equilibrium",
      "Acids, Bases and Salts",
      "Organic Chemistry",
      "Biochemistry",
      "Environmental Chemistry-I (The Atmosphere)",
      "Environmental Chemistry-II (Water)",
      "Analytical Chemistry",
      "Industrial Chemistry",
    ],
    prerequisites: "Must clear 8 standard",
    examCode: "CHEM 9702",
    featured: true,
  },
  {
    id: "CRS-3385",
    code: "VVA-EX926-BIO",
    title: "BIOLOGY",
    track: "cambridge-a-levels",
    trackLabel: "Ziauddin",
    department: "Sciences",
    gradeLevel: "Grades 9 - 10",
    weeklyHours: 6,
    instructor: "Tamseel Fatima",
    instructorTitle: "M.Phil. in Biological Sciences",
    description:
      "Cell biology, genetics, evolution, human physiology, ecology, biodiversity, microbiology, and molecular biology designed to build strong scientific concepts and prepare students for higher education in Biology and related fields.",
    syllabus: [
      "Homeostasis",
      "Coordination and Control",
      "Support and Movement",
      "Reproduction",
      "Inheritance",
      "Man and His Environment",
      "Biotechnology",
      "Pharmacology",
    ],
    prerequisites: "Must clear 8 standard",
    examCode: "CIE 9709",
    featured: true,
  },
  {
    id: "CRS-9023",
    code: "VVA-EX647-MTH",
    title: "MATHEMATICS",
    track: "cambridge-a-levels",
    trackLabel: "Ziauddin",
    department: "Mathematics",
    gradeLevel: "Grades 9 - 10",
    weeklyHours: 5,
    instructor: "Hania batool",
    instructorTitle: "M.Eng. Software Engineering (Imperial College)",
    description:
      "A comprehensive mathematics programme covering algebra, geometry, trigonometry, functions, calculus, statistics, probability, vectors, and problem-solving, designed to build strong mathematical concepts, logical thinking, analytical skills, and exam readiness.",
    syllabus: [
      "Real and Complex Numbers",
      "Logarithms",
      "Algebraic Expression and Formulas",
      "Factorization",
      "Algebraic Manipulation",
      "Linear Equation and Inequalities",
      "Linear Graphs and their Applications",
      "Quadratic Equations",
      "Congruent Triangles",
      "Parallelograms and Triangles",
      "Line Bisectors and Angles Bisectors",
      "Sides and Angles of a Triangle",
      "Practical Geometry – Triangles",
      "Theorems Related with Area",
      "Projection of a Side of a Triangle",
      "Introduction to Coordinate Geometry / Analytical Geometry",
    ],
    prerequisites: "Must clear 8 standard",
    examCode: "CIE 9618",
    featured: true,
  },
  {
    id: "CRS-1294",
    code: "VVA-EX841-ENG",
    title: "ENGLISH",
    track: "advanced-placement",
    trackLabel: "College Board AP",
    department: "Humanities",
    gradeLevel: "Grades 9 - 10",
    weeklyHours: 5,
    instructor: "Syeda Fabiha",
    instructorTitle: "M.A. in English Literature",
    description:
      "A comprehensive English programme covering grammar, vocabulary, reading comprehension, creative writing, essay writing, literature, speaking, and communication skills, designed to build language proficiency, critical thinking, confidence, and exam readiness.",
    syllabus: [
      "Contribution of Notable Leader",
      "Labor and People Rights",
      "Practicing Positive Work Ethics",
      "Media for Information and Reflection",
      "Respecting Self and Other",
      "Character Building",
      "Praising Nature",
      "Civic Sense and Civic Activity",
    ],
    prerequisites: "Must clear 8 standard",
    examCode: "College Board AP Calc BC",
    featured: true,
  },
  {
    id: "CRS-7741",
    code: "VVA-EX503-CSC",
    title: "COMPUTER SCIENCE",
    track: "advanced-placement",
    trackLabel: "College Board AP",
    department: "Computer Science",
    gradeLevel: "Grades 9 - 10",
    weeklyHours: 4,
    instructor: "Waniya Khan",
    instructorTitle: "M.Sc. in Computer Science",
    description:
      "A comprehensive computer science programme covering programming fundamentals, algorithms, data structures, databases, computer networks, web development, cybersecurity, and emerging technologies, designed to build strong technical concepts, problem-solving skills, logical thinking, and exam readiness.",
    syllabus: [
      "Problem Solving and Algorithm Design",
      "Basics of Programming In C++",
      "INPUT/OUTPUT Handling In C++",
      "Control Structures",
      "Functions",
      "Digital Logic and Design",
      "Introduction to Scratch",
    ],
    prerequisites: "Must clear 8 standard",
    examCode: "College Board AP CSA",
  },
  {
    id: "CRS-8832",
    code: "VVA-EX318-PHY",
    title: "PHYSICS",
    track: "advanced-placement",
    trackLabel: "College Board AP",
    department: "Sciences",
    gradeLevel: "Grades 9 - 10",
    weeklyHours: 5,
    instructor: "Syed Muhammad Salman Naqvi",
    instructorTitle: "M.Sc. in Applied Physics",
    description:
      "A comprehensive physics programme covering mechanics, motion, forces, energy, waves, electricity, magnetism, thermal physics, optics, and modern physics, designed to build strong concepts, analytical thinking, problem-solving skills, and exam readiness.  ",
    syllabus: [
      "Physical Quantities and Measurement",
      "Kinematics",
      "Dynamics",
      "Turning Effect of Forces",
      "Forces and Matter",
      "Gravitation",
      "Properties of Matter",
      "Energy Sources and Transfer of Energy",
      "Thermal Properties of Matter",


    ],
    prerequisites: "Must clear 8 standard",
    examCode: "College Board AP Chem",
  },
 
];

export const MOCK_FACULTY: FacultyMember[] = [
  {
    id: "fac-jenkins",
    name: "Wara Batool",
    role: "Academic Director",
    department: "Sciences",
    education: "M.Phill. in Chemistry / Physical Sciences",
    experienceYears: 14,
    bio: "Wara Batool is a dedicated Science educator specializing in Chemistry for grades 9–10. She focuses on clear, concept-based teaching and making science engaging and easy to understand for students.",
    specialization: "Chemistry (Grades 9-10)",
    availability: "Tuesdays & Thursdays, 16:00 - 18:00 GST",
    officeHours: "Tuesdays & Thursdays, 16:00 - 18:00 GST",
    avatarInitials: "WB",
  },
  {
    id: "fac-thompson",
    name: "Tamseel Fatima",
    role: "Science Professor",
    department: "Sciences",
    education: "M.Phil. in Biological Sciences",
    experienceYears: 18,
    bio: "Tamseel Fatima is a passionate educator specializing in Biology for grades 9–10. She focuses on concept-based, engaging, and student-centered learning.",
    specialization: "Biology (Grades 9-10)",
    availability: "Daily (Morning & Evening Cohorts)",
    officeHours: "Wednesdays & Fridays, 15:00 - 17:00 GST",
    avatarInitials: "TF",
  },
  {
    id: "fac-chen",
    name: "Hania Batool",
    role: "Mathematics Teacher",
    department: "Mathematics",
    education: "M.Sc. in Mathematics",
    experienceYears: 11,
    bio: "Hania Batool is an experienced mathematics educator specializing in foundational to advanced math for grades 1–10, focusing on problem-solving and analytical clarity.",
    specialization: "Mathematics (Grades 1-10)",
    availability: "Mon, Tue, Thu, Fri",
    officeHours: "Thursdays, 14:00 - 16:00 GST",
    avatarInitials: "HB",
  },
  {
    id: "fac-vance",
    name: "Syeda Fabiha",
    role: "English Teacher",
    department: "Humanities",
    education: "M.A. in English Literature",
    experienceYears: 15,
    bio: "Syeda Fabiha specializes in English language and literature for grades 1–10. She focuses on clear communication, language development, and interactive learning.",
    specialization: "English (Grades 1-10)",
    availability: "Daily, 11:00 - 13:00 GST",
    officeHours: "Daily, 11:00 - 13:00 GST",
    avatarInitials: "SF",
  },
  {
    id: "fac-ross",
    name: "Waniya Khan",
    role: "Computer Teacher",
    department: "Computer Science",
    education: "M.Sc. in Computer Science",
    experienceYears: 12,
    bio: "Waniya Khan teaches Computer Studies for grades 1–10. She focuses on practical digital literacy, logic building, and foundational computing skills.",
    specialization: "Computer (Grades 1-10)",
    availability: "Mondays & Wednesdays, 14:00 - 16:00 GST",
    officeHours: "Mondays & Wednesdays, 14:00 - 16:00 GST",
    avatarInitials: "WK",
  },
  {
    id: "fac-bailey",
    name: "Syed Muhammad Salman Naqvi",
    role: "Co-Ordinator",
    department: "Sciences",
    education: "M.Sc. in Applied Physics",
    experienceYears: 13,
    bio: "Syed Muhammad Salman Naqvi coordinates curriculum execution and teaches Physics for grades 9–10, focusing on practical physics concepts and academic excellence.",
    specialization: "Physics (Grades 9-10)",
    availability: "Mon, Wed, Fri",
    officeHours: "Wednesdays, 13:00 - 15:00 GST",
    avatarInitials: "SM",
  },
];

export const MOCK_TIMETABLE_FULL: TimetableEntry[] = [
  {
    id: "tt-mon-1",
    day: "Monday",
    baseTimeGst: "09:00 - 10:15",
    subject: "Cambridge AS-Level Physics",
    topic: "Rotational Dynamics & Torque Analysis",
    teacher: "Dr. Sarah Jenkins",
    teacherAvatar: "SJ",
    roomCode: "PHY-301",
    status: "completed",
    slidesAvailable: true,
    recordingAvailable: true,
  },
  {
    id: "tt-mon-2",
    day: "Monday",
    baseTimeGst: "10:45 - 12:00",
    subject: "Pure Mathematics (P1 & P3)",
    topic: "Integration by Substitution & Partial Fractions",
    teacher: "Prof. Mark Thompson",
    teacherAvatar: "MT",
    roomCode: "MAT-204",
    status: "live",
    slidesAvailable: true,
    recordingAvailable: false,
  },
  {
    id: "tt-mon-3",
    day: "Monday",
    baseTimeGst: "13:00 - 14:15",
    subject: "Computer Science (A-Level)",
    topic: "Binary Trees & Graph Traversal Algorithms in Python",
    teacher: "Eng. Alex Chen",
    teacherAvatar: "AC",
    roomCode: "CS-410",
    status: "upcoming",
    slidesAvailable: true,
    recordingAvailable: false,
  },
  {
    id: "tt-mon-4",
    day: "Monday",
    baseTimeGst: "15:00 - 16:00",
    subject: "Academic Advisory & 1-on-1",
    topic: "University Application Portfolio & Mock Interview",
    teacher: "Ms. Rebecca Vance",
    teacherAvatar: "RV",
    roomCode: "ADV-101",
    status: "upcoming",
    slidesAvailable: false,
    recordingAvailable: false,
  },
];

export const MOCK_ASSIGNMENTS: Assignment[] = [
  {
    id: "asg-phy-4",
    title: "Physics Problem Set 4: Rotational Inertia & Angular Momentum",
    course: "Cambridge AS-Level Physics",
    courseCode: "PHY-9702",
    dueDate: "Today at 18:00 GST",
    status: "pending",
    instructions: "Complete questions 1 through 8 from Chapter 6. Show all free-body diagrams and algebraic derivations clearly.",
    urgency: "high",
  },
  {
    id: "asg-mat-7",
    title: "Pure Math Worksheet: Integration by Parts & Definite Integrals",
    course: "Pure Mathematics 1 & 3",
    courseCode: "MAT-9709",
    dueDate: "Tomorrow at 23:59 GST",
    status: "submitted",
    score: "96 / 100 (A*)",
    feedback: "Excellent integration proofs. Pay attention to constant of integration in indefinite forms.",
    instructions: "Submit scanned solutions to worksheet exercises 14A and 14B.",
    urgency: "normal",
  },
  {
    id: "asg-cs-3",
    title: "Python Data Structures: Custom Binary Search Tree & AVL Balancing",
    course: "Computer Science & Python",
    courseCode: "CS-9618",
    dueDate: "Friday at 17:00 GST",
    status: "pending",
    instructions: "Implement an insert, delete, and in-order traversal method in Python with unit tests.",
    urgency: "normal",
  },
];

export const CURRENCY_RATES = {
  USD: { symbol: "$", rate: 1.0, name: "US Dollar (USD)" },
  GBP: { symbol: "£", rate: 0.78, name: "British Pound (GBP)" },
  EUR: { symbol: "€", rate: 0.92, name: "Euro (EUR)" },
  AED: { symbol: "AED ", rate: 3.67, name: "UAE Dirham (AED)" },
  SAR: { symbol: "SAR ", rate: 3.75, name: "Saudi Riyal (SAR)" },
  PKR: { symbol: "Rs ", rate: 278.5, name: "Pakistani Rupee (PKR)" },
  CAD: { symbol: "CA$", rate: 1.36, name: "Canadian Dollar (CAD)" },
  AUD: { symbol: "AU$", rate: 1.52, name: "Australian Dollar (AUD)" },
};

